// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using asp.net_ReactJs_CRUD.Data;

#nullable disable

namespace asp.net_ReactJs_CRUD.Data.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20220831175859_StartMigration")]
    partial class StartMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.8");

            modelBuilder.Entity("asp.net_ReactJs_CRUD.Models.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1000000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("PostId");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            PostId = 1,
                            Content = "Post 1 Content",
                            Title = "Post 1"
                        },
                        new
                        {
                            PostId = 2,
                            Content = "Post 2 Content",
                            Title = "Post 2"
                        },
                        new
                        {
                            PostId = 3,
                            Content = "Post 3 Content",
                            Title = "Post 3"
                        },
                        new
                        {
                            PostId = 4,
                            Content = "Post 4 Content",
                            Title = "Post 4"
                        },
                        new
                        {
                            PostId = 5,
                            Content = "Post 5 Content",
                            Title = "Post 5"
                        },
                        new
                        {
                            PostId = 6,
                            Content = "Post 6 Content",
                            Title = "Post 6"
                        },
                        new
                        {
                            PostId = 7,
                            Content = "Post 7 Content",
                            Title = "Post 7"
                        },
                        new
                        {
                            PostId = 8,
                            Content = "Post 8 Content",
                            Title = "Post 8"
                        },
                        new
                        {
                            PostId = 9,
                            Content = "Post 9 Content",
                            Title = "Post 9"
                        },
                        new
                        {
                            PostId = 10,
                            Content = "Post 10 Content",
                            Title = "Post 10"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
